spring:
        application:
                name: tokenexample  # 애플리케이션 이름 설정 (Spring Boot 내부에서 사용됨)

        datasource:
                url: jdbc:mysql://localhost:3306/java_basic?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
                driver-class-name: com.mysql.cj.jdbc.Driver
                username: root  # MySQL 데이터베이스 사용자명
                password: "1234"  # MySQL 데이터베이스 비밀번호 (실제 환경에서는 보안상 숨겨야 함)

        server:
                port: 8081  # 애플리케이션이 실행될 포트 설정 (기본값: 8080 → 8081로 변경)

        mybatis:
                mapper-locations: classpath:mappers/*.xml  # MyBatis Mapper XML 파일 경로 설정
                type-aliases-package: com.example.spring.tokenexample.model  # MyBatis에서 사용할 모델 패키지 지정

        jwt:
                issuer: test@gmail.com  # JWT 발급자 (iss 필드에 해당)
                secret_key: 55DQ7XtZjKEuftetbQMtw0geU9SS1rR/fbrPOAqIQ2UUPJ+crjXRoLppDtreyvim53v3U6+hTLcbunHlxlNGlA==
                # JWT 서명(Signature)에 사용할 비밀 키 (Base64 인코딩된 HMAC SHA 키)
